spring.application.name=backend
# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:condominiodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console web do H2 (para você inspecionar as tabelas pelo navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate gera/atualiza as tabelas automaticamente a partir das Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true